spring:
  application:
    name: springBatch
  datasource:
    url: jdbc:mysql://localhost:3306/springbatchdb?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
#  batch:
#    job:
#      enabled: false
server:
  servlet:
    context-path: /springBatch
  port: 80
