spring:
  application:
    name: springBatch
  datasource-batch:
    jdbc-url: jdbc:mysql://localhost:3306/springbatchdb?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    minimum-idle: 5
    idle-timeout: 180000
    maximum-pool-size: 11
    auto-commit: true
    pool-name: BatchRepository1
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1
  datasource-documents:
    jdbc-url: jdbc:mysql://localhost:3306/documents?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    minimum-idle: 5
    idle-timeout: 180000
    maximum-pool-size: 22
    auto-commit: true
    pool-name: DocumentsRepository2
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1

  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect


#  main:
#    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
server:
  servlet:
    context-path: /springBatch
  port: 80


